dist: bionic
language: python
python:
  - 3.6
install:
  - sudo bash install.sh
  - sudo pip install -r requirements.txt
script:
  - sudo pytest -s
  - curl -i http://localhost:8000
  - curl -i http://localhost:8000/processes
