---
- name: Deploy Process-API application
  hosts: all
  gather_facts: false
  become: yes

  handlers:

  - name: Restart Process-API gunicorn service
    systemd:
      state: restarted
      daemon_reload: yes
      name: process-api.service

  tasks:

  - name: Update repository cache and install packages
    apt:
      force_apt_get: yes
      update_cache: yes
      name: ["python3-pip", "python3-venv"]

  - name: Checkout Process-API Git repository
    git:
      repo: https://github.com/ep-process-api/process-api.git
      dest: /opt/process-api

  - name: Create & activate Python virtual environment + install dependencies
    shell: "{{ item }}"
    with_items:
      - python3 -m venv venv
      - . .venv/bin/activate && pip3 install -r requirements.txt
    args:
      chdir: /opt/process-api/

  - name: Copy gunicorn systemd config files
    copy:
      src: configs/process-api.service
      dest: /etc/systemd/system/
    notify: Restart Process-API gunicorn service
